site_name: '数字化指南 ཨང་བསྒྱུར་ལམ་སྟོན། BUDA Digitization Guidelines'
site_description: '数字化指南 ཨང་བསྒྱུར་ལམ་སྟོན། Digitization Guidelines'

theme: windmill

pages:
- Introduction 介绍 ངོ་སྤྲོད།: index.md
- Workflow:
  - 工作流程: workflow/workflow-cn.md
  - ལས་འཆར།: workflow/workflow-bo.md
  - Workflow: workflow/workflow-en.md
# - Theory:
  # - theory/images.md

- Resources 资源 : resources.md

extra:
    # history_buttons: true
    logo: 'img/bdrc-logo.png'
